server:
  port: 8001
  servlet:
    session:
      timeout: 86400


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/star-code?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root  #数据库名、用户名和密码改为自己的
    driver-class-name: com.mysql.cj.jdbc.Driver






#mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mapper/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: org.javatop.usercenter.domain
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#配置控制台打印日志Debug
logging:
  level:
    org.javatop.usercenter.mapper: debug
