server:
  port: 8001


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/star-code?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root  #数据库名、用户名和密码改为自己的
    driver-class-name: com.mysql.cj.jdbc.Driver





#mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mapper/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: org.javatop.usercenter.domain
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

#配置控制台打印日志Debug
logging:
  level:
    org.javatop.usercenter.mapper: debug
